name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - name: cml_run
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run:
          /usr/bin/python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python train.py
          
          echo "MODEL METRICS"
          cat metrics.txt
